"""empty message

Revision ID: 156121311fb2
Revises: 85cfddce1ab7
Create Date: 2020-05-08 14:40:16.376064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156121311fb2'
down_revision = '85cfddce1ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isModerator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isModerator', sa.BOOLEAN(), server_default=sa.text("'False'"), nullable=False))
    # ### end Alembic commands ###
